[default]
AltRight >> ScrollLock
CapsLock >> ControlLeft
# (CapsLock AltLeft){L} >> (ControlLeft Meta){ArrowRight}
# (CapsLock AltLeft){H} >> (ControlLeft Meta){ArrowLeft}
[class=/krita/i]
NumpadDivide >> Control{Z}
NumpadMultiply >> (Control Shift){Z}
Numpad7 >> Shift
Numpad8 >> ControlLeft
Numpad4 >> Space
Numpad6 >> M
[class=/ArtRage/i]
NumpadDivide >> Control{Z}
NumpadMultiply >> Control{Y}
Numpad7 >> Shift
Numpad8 >> AltLeft
Numpad4 >> Space
Numpad6 >> H
Numpad1 >> ControlLeft
