[default]
AltRight >> ScrollLock
CapsLock >> ControlLeft

(ControlLeft AltLeft){T} >> $(alacritty) ^
OSLeft{Enter} >> $(alacritty) ^
OSLeft{E} >> $(dolphin) ^
OSLeft{I} >> $(plasma-open-settings) ^
OSLeft{C} >> $(emacs) ^
OSLeft{M} >> $(thunderbird) ^
OSLeft{W} >> $(firefox) ^
OSLeft{S} >> $(pamac-manager) ^
OSLeft{P} >> $(keepassxc) ^

[class=/krita/i]
NumpadDivide >> Control{Z}
NumpadMultiply >> (Control Shift){Z}
Numpad7 >> Shift
Numpad8 >> ControlLeft
Numpad4 >> Space
Numpad6 >> M

[class=/ArtRage/i]
NumpadDivide >> Control{Z}
NumpadMultiply >> Control{Y}
Numpad7 >> Shift
Numpad8 >> AltLeft
Numpad4 >> Space
Numpad6 >> H
Numpad1 >> ControlLeft
