[/home/jdyer/DCIM/Camera]
Sort=mtime;descending;
ViewMode=icon
ShowHidden=true

[/home/jdyer/DCIM/Screenshots]
Sort=mtime;descending;
ViewMode=icon
ShowHidden=true
Columns=name:200;ext;desc;size;mtime;

[/home/jdyer/DCIM/content]
Sort=name;ascending;
ViewMode=list
ShowHidden=true

[/home/jdyer/nas]
Sort=name;ascending;
ViewMode=list
Columns=name:200;dirname;desc:93;size;mtime;
ShowHidden=true

[/mnt/veracrypt1/Documents]
Sort=name;ascending;
ViewMode=list
Columns=name:200;dirname;desc:93;size;mtime;
ShowHidden=true

[/home/jdyer/DCIM/content/house]
Sort=mtime;descending;
ViewMode=list
Columns=name:200;dirname;desc:93;size;mtime;
ShowHidden=true

[search:///]
Sort=name;ascending;
ViewMode=list
ShowHidden=true
