# Zenburn tinted with pywal (10% pywal)
[colors-dark]
foreground=dfdcca
background=221f1f
regular0=221f1f
regular1=ca8c8a
regular2=879878
regular3=d1b788
regular4=799e9c
regular5=df8eb9
regular6=9edad7
regular7=dfdcca
bright0=6d6b68
bright1=d89a98
bright2=c0dcb1
bright3=eed4a5
bright4=96c9c7
bright5=fcaad6
bright6=baf6f0
bright7=fefbf8
